- name: install the elastic search component
  hosts: elasticsearch
  become: yes
  tasks:
    - name: Install the java
      ansible.builtin.yum:
        name: java-11-openjdk-devel
        state: installed

    - name: copying the repo file to yum repository
      ansible.builtin.copy:
        src: elasticsearch.repo
        dest: /etc/yum.repos.d/elasticsearch.repo

    - name: Install the elastic search
      ansible.builtin.yum:
        name: elasticsearch 
        state: installed

    # - name: Replace two elements
    #   ansible.builtin.replace:
    #     path: /etc/elasticsearch/elasticsearch.yml  # Replace with the actual file path
    #     regexp:
    #       - '#network.host: 192.168.0.1'  # First element's regex pattern
    #       - '#http.port: 9200'  # Second element's regex pattern
    #     replace:
    #       - 'network.host: 0.0.0.0'  # First element's replacement value
    #       - 'http.port: 9200'  # Second element's replacement value

    - name: Add Line Under Discovery Section
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^discovery\..*'  # Match any line starting with 'discovery.'
        insertafter: '^discovery:'  # Insert the line after the 'discovery:' line
        line: 'discovery.type: single-node'  # Replace with your desired line


    - name: enable the service
      ansible.builtin.service:
        name: elasticsearch
        enabled: yes
